### PR TITLE
Anindya/graph nn

### PR DESCRIPTION
**Pull request by Anindyadeep**
Please check the content (excluding the typos and other). If this is fine, I will correct the typos, and other grammatical mistakes. Sorry for being late.

### CODE REVIEW

**Comment by python-engineer** [comment]
Hi, cool article! Content looks fine. Where did you get those images from?

**Comment by Anindyadeep** [comment]
Ok, So the very first image, and the word embedding were taken from internet, just by image search.  And all other images are original (I made from my tablet.)If referencing is required, please mention how to references those. Also, if these looks fine then I will go over for the typos, and ig we would be cool for merge. Also, after that I will go for the next sets of topics, slowly diving to the math and the code part. Thank you.

**Comment by python-engineer** [comment]
wow they are really cool! Yes if taken from internet then please mention the source below the image. Just write (Source: xzy.com)
This is great. By the way my website supports Latex if you want to use it for your math equations.

**Comment by Anindyadeep** [comment]
Yeahh that would be greatt! ... As from the next set of tutorials i will be going to some math. So give me todays time, i will head over for pr after checking the typos. Sounds cool ig.

**Review by Anindyadeep — COMMENTED** [review]
Typos are fixed.

**Comment by Anindyadeep** [comment]
Okay, so changes are made, also added the source of images in the `alt` part of the images link. I hope this is now able to get merged. Thank you.

**Comment by Anindyadeep** [comment]
Hi, its been days, but I saw, its still not merged. Its there any sort of problem?
Thank you.

**Comment by python-engineer** [comment]
Hi, sorry I've been busy the last days. The content looks good, I just need to transform it to normal markdown format before I can merge it. But I can take care of it.
But also before I can merge it, I need your author's informations so that I can put you up on the website. Have a look at the README for instructions.
Great article!

**Comment by Anindyadeep** [comment]
Thanks. I will provide the author information. Also next set of articles on the way.

**Comment by Anindyadeep** [comment]
yeah!, I have added the information.

**Comment by python-engineer** [comment]
Thank you! Your article is live on my website and your author profile is here: https://www.python-engineer.com/authors/anindyadeep/

**Comment by Anindyadeep** [comment]
Thank you for the merge. I will be starting to upload the next part of this blog soon.

**Pull request merged**
